name: Build

on:
  push:
    tags-ignore:
      - "v*"
    branches:
      - main
  pull_request:
    tags-ignore:
      - "v*"
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the current repo
      - uses: actions/checkout@v2
      # Install required JDK
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 16
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      # Retrieve cached dependencies
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Testing if the gradlew build succeed
      - name: Testing build
        run: ./gradlew build