name: Manual release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/ver')
    steps:
      # Checkout the current repo
      - uses: actions/checkout@v2
      # Install required JDK
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 16
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      # Retrieve cached dependencies
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Build Release
      - name: Build with Gradle (Release)
        if: ${{ !contains(github.ref,'rc') }}
        run: ./gradlew -Prelease.useLastTag=true final
      # Build PreRelease
      - name: Build with Gradle (PreRelease)
        if: contains(github.ref,'rc')
        run: ./gradlew -Prelease.useLastTag=true candidate
      # Package artifact
      - name: Package jar into artifact
        uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: build/libs